---
title: "demo1"
author: "Reinhard Simon"
date: "9/21/2018"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

## Init

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Definir secuencias

- seq1
- seq2
- seq3

```{r define_sequences}
library(Biostrings)

 s1 <- 
    DNAString("ACTTCACCAGCTCCCTGGCGGTAAGTTGATCAAAGGAAACGCAAAGTTTTCAAG")
  s2 <-
    DNAString("GTTTCACTACTTCCTTTCGGGTAAGTAAATATATAAATATATAAAAATATAATTTTCATC")

  # First use a fixed substitution matrix
  mat <- nucleotideSubstitutionMatrix(match = 1, mismatch = -3, baseOnly = TRUE)
  

  mat
```



```{r}

  localAlign <-
    pairwiseAlignment(s1, s2, type = "local", substitutionMatrix = mat,
                      gapOpening = 5, gapExtension = 2)
  
  as.character(localAlign)
  
  aligned(subject(localAlign))
 
```

```{r}

  globalAlign <-
    pairwiseAlignment(s1, s2, substitutionMatrix = mat,
                      gapOpening = 5, gapExtension = 2)

as.character(globalAlign)
```





